export const FETCH_ACCOUNT = 'mix/FETCH_ACCOUNT';
export const FETCH_ACCOUNT_SUCCESS = 'mix/FETCH_ACCOUNT_SUCCESS';
export const FETCH_BLOCKS = 'mix/FETCH_BLOCKS';
export const FETCH_BLOCKS_SUCCESS = 'mix/FETCH_BLOCKS_SUCCESS';
export const FETCH_TRANSACTION = 'mix/FETCH_TRANSACTION';
export const FETCH_TRANSACTION_SUCCESS = 'mix/FETCH_TRANSACTION_SUCCESS';
