export const FETCH_ACCOUNT = 'mix/FETCH_ACCOUNT';
export const FETCH_ACCOUNT_SUCCESS = 'mix/FETCH_ACCOUNT_SUCCESS';
export const FETCH_BLOCKS = 'mix/FETCH_BLOCKS';
export const FETCH_BLOCKS_SUCCESS = 'mix/FETCH_BLOCKS_SUCCESS';
export const FETCH_TRANSACTIONS = 'mix/FETCH_TRANSACTIONS';
export const FETCH_TRANSACTIONS_SUCCESS = 'mix/FETCH_TRANSACTIONS_SUCCESS';
